package dml.largescaletaskmanagement.service.repositoryset;

import dml.largescaletaskmanagement.repository.LargeScaleSingletonTaskRepository;
import dml.largescaletaskmanagement.repository.LargeScaleTaskSegmentRepository;
import dml.largescaletaskmanagement.repository.SegmentProcessingTimeoutHandlingStrategyRepository;

public interface LargeScaleSingletonTaskServiceRepositorySet {
    LargeScaleSingletonTaskRepository getLargeScaleSingletonTaskRepository();

    LargeScaleTaskSegmentRepository getLargeScaleTaskSegmentRepository();

    SegmentProcessingTimeoutHandlingStrategyRepository getSegmentProcessingTimeoutHandlingStrategyRepository();
}
